# Generated by Django 5.0.6 on 2024-06-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('lien', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projet_images/')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.projet')),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='tags',
            field=models.ManyToManyField(related_name='projets', to='main.tag'),
        ),
    ]
